### PR TITLE
Fix JSON deserialization of TimeRestriction structured query model class

### LINKED ISSUE #212: TimeRestriction model class requires closed time interval during deserialization
## **IS:**
The `de.numcodex.sq2cql.model.structured_query.TimeRestriction::fromJsonNode` method requires both attributes `afterDate` and `beforeDate` to be present even though providing only one (or even none) would be valid.

```java
    public static TimeRestriction fromJsonNode(JsonNode node) {
        return TimeRestriction.create(node.get("afterDate").asText(), node.get("beforeDate").asText());
    }
```

## **SHOULD:**
The deserialization should not require any of the two attributes to have a value.

### PR DESCRIPTION
**Pull request by paulolaup**
Closes: #212

### CODE REVIEW

File: src/test/java/de/numcodex/sq2cql/model/structured_query/TimeRestrictionTest.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+import static java.time.format.DateTimeFormatter.ISO_DATE;
+
+import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
+import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.junit.jupiter.api.Assertions.assertNull;
+
+public class TimeRestrictionTest {
+
+    @Test
+    void fromJsonNode() {
```
Comment (alexanderkiel) [inline src/test/java/de/numcodex/sq2cql/model/structured_query/TimeRestrictionTest.java]: Can you please write one test for each scenario? Also please use AssertJ assertions. I like to move towards them. The text from assertDoesNotThrow can go into @DisplayName of the individual tests. 

On top of that you do not test `fromJsonNode` at all. Instead, you test `create`. You can use Run with Code Coverage in IntelliJ to see that.

File: src/main/java/de/numcodex/sq2cql/model/structured_query/TimeRestriction.java [hunk 2]
```diff
@@ -30,16 +31,18 @@ public static TimeRestriction create(@JsonProperty("afterDate") String afterDate
...
-            return TimeRestriction.of(LocalDate.parse(afterDate), LocalDate.of(2040, 1, 1));
+            return TimeRestriction.of(LocalDate.parse(afterDate), LocalDate.MAX);
         } else {
             return TimeRestriction.of(LocalDate.parse(afterDate), LocalDate.parse(beforeDate));
         }
     }
 
     public static TimeRestriction fromJsonNode(JsonNode node) {
-        return TimeRestriction.create(node.get("afterDate").asText(), node.get("beforeDate").asText());
+        final var afterDate = Optional.ofNullable(node.get("afterDate")).map(JsonNode::asText).orElse(null);
```
Comment (alexanderkiel) [inline src/main/java/de/numcodex/sq2cql/model/structured_query/TimeRestriction.java]: I would not use `final` on local variables, because it should be obvious not to reassign them.

**Review by alexanderkiel — CHANGES_REQUESTED** [review]

**Review by alexanderkiel — DISMISSED** [review]

**Review by alexanderkiel — APPROVED** [review]
